### ISSUE TITLE
Example payload

### ISSUE THREAD

**Issue by 0xjtru** [EdOverflow/operation-red#3]
Having an example payload for the payloads.txt file would be helpful

**Comment by EdOverflow** [comment]
Could you give me an example? What exactly do you mean by an "example payload"?

**Comment by 0xjtru** [comment]
Sorry, I don't think 'payloads.txt' was uploaded when I started playing around. 

Closing as it's a nonissue

**Comment by EdOverflow** [comment]
Ah, I see. No worries.
